.TH MYMEMORY 1 "MARCH 2018" UPEM "myMemory manual"
.SH NAME
myMemory.py \- Memory paging simulator
.SH SYNOPSIS
myMemory.py [-h] -s <main mem size> -v <virtual mem size> -a <fifo>
.SH DESCRIPTION
.B foo
frobnicates the bar library by tweaking internal
symbol tables. By default it parses all baz segments
and rearranges them in reverse order by time for the
.BR xyzzy (1)
linker to find them. The symdef entry is theni compressed
using the WBG (Whiz-Bang-Gizmo) algorithm.
All files are processed in the order specified.
.SH OPTIONS
.IP -b
Do not write `busy' to stdout while processing.
.IP "-c config-file"
Use the alternate system wide
.I config-file
instead of
.IR /etc/foo.conf .
This overrides any
.B FOOCONF
environment variable.
.IP -a
In addition to the baz segments, also parse the
blurfl headers.
.IP -r
Recursive mode. Operates as fast as lightning
at the expense of a megabyte of virtual memory.
.SH FILES
.I /etc/foo.conf
.RS
The system wide configuration file. See
.BR foo (5)
for further details.
.RE
.I ~/.foorc
.RS
Per user configuration file. See
.BR foo (5)
for further details.
.SH ENVIRONMENT
.IP FOOCONF
If non-null the full pathname for an alternate system wide
.IR foo.conf .
Overridden by the
.B -c
option.
.SH DIAGNOSTICS
The following diagnostics may be issued on stderr:
 
Bad magic number.
.RS
The input file does not look like an archive file.
.RE
Old style baz segments.
.RS
.B foo
can only handle new style baz segments. COBOL
object libraries are not supported in this version.
.SH EXAMPLE
.nf
% ./myMemory.py -s 3 -v 5 -a fifo
> 7	7xx
> 0	70x
> 1	701
> 2	201
> p	201	7xxxx
> 0	201
> 3	231
> p	231	70xxx
> 0	230
> p	230	71xxx
> 4	430
> 2	420
> p	420	713xx
> x
.fi
.SH AUTHORS
Pacien TRAN-GIRARD
Adam NAILI

